version: 2
updates:
- package-ecosystem: npm
  directory: /
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  groups:
    npm-root-patch-minor:
      applies-to: version-updates
      patterns:
      - '*'
      update-types:
      - patch
      - minor
    npm-root-security:
      applies-to: security-updates
      patterns:
      - '*'
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
  labels:
  - dependencies
  - type:chore
  - area:ci
- package-ecosystem: npm
  directory: /apps/web
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  groups:
    npm-apps-web-patch-minor:
      applies-to: version-updates
      patterns:
      - '*'
      update-types:
      - patch
      - minor
    npm-apps-web-security:
      applies-to: security-updates
      patterns:
      - '*'
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
  labels:
  - dependencies
  - type:chore
  - area:ci
- package-ecosystem: npm
  directory: /apps/desktop
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  groups:
    npm-apps-desktop-patch-minor:
      applies-to: version-updates
      patterns:
      - '*'
      update-types:
      - patch
      - minor
    npm-apps-desktop-security:
      applies-to: security-updates
      patterns:
      - '*'
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
  labels:
  - dependencies
  - type:chore
  - area:ci
- package-ecosystem: npm
  directory: /apps/remake-web
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  groups:
    npm-apps-remake-web-patch-minor:
      applies-to: version-updates
      patterns:
      - '*'
      update-types:
      - patch
      - minor
    npm-apps-remake-web-security:
      applies-to: security-updates
      patterns:
      - '*'
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
  labels:
  - dependencies
  - type:chore
  - area:ci
- package-ecosystem: npm
  directory: /apps/web/public/ruffle
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  groups:
    npm-apps-web-public-ruffle-patch-minor:
      applies-to: version-updates
      patterns:
      - '*'
      update-types:
      - patch
      - minor
    npm-apps-web-public-ruffle-security:
      applies-to: security-updates
      patterns:
      - '*'
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
  labels:
  - dependencies
  - type:chore
  - area:ci
- package-ecosystem: gradle
  directory: /android
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  groups:
    gradle-android-patch-minor:
      applies-to: version-updates
      patterns:
      - '*'
      update-types:
      - patch
      - minor
    gradle-android-security:
      applies-to: security-updates
      patterns:
      - '*'
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
  labels:
  - dependencies
  - type:chore
  - area:ci
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  groups:
    github-actions-root-patch-minor:
      applies-to: version-updates
      patterns:
      - '*'
      update-types:
      - patch
      - minor
    github-actions-root-security:
      applies-to: security-updates
      patterns:
      - '*'
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
  labels:
  - dependencies
  - type:chore
  - area:ci
